'use client'
import { FormEvent, useState } from 'react'
import { supabaseBrowser } from '@/lib/supabase-browser'
import { useRouter } from 'next/navigation'

export default function Register(){
 const router=useRouter(); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [ref,setRef]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');const s=supabaseBrowser();const {data,error}=await s.auth.signUp({email,password,options:{data:{full_name:name}}});if(error){setError(error.message);setBusy(false);return}if(data.user&&ref){await s.rpc('claim_referral_code',{p_referral_code:ref})}router.push('/dashboard');setBusy(false)}
 return <main className="min-h-screen grid place-items-center bg-[#05070b] text-white px-6 py-10"><form onSubmit={submit} className="w-full max-w-md rounded-3xl border border-white/10 bg-white/[.04] p-8"><h1 className="text-3xl font-black"><span className="text-cyan-400">NEROX</span> AISO</h1><p className="mt-2 text-slate-400">Create your account</p>{[['Name',name,setName,'text'],['Email',email,setEmail,'email'],['Password',password,setPassword,'password']].map(([label,val,set,type]:any)=><label key={label} className="mt-4 block text-sm">{label}<input required type={type} value={val} onChange={e=>set(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 p-3 outline-none"/></label>)}<label className="mt-4 block text-sm">Referral code <span className="text-slate-500">(optional)</span><input value={ref} onChange={e=>setRef(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 p-3 outline-none"/></label>{error&&<p className="mt-4 text-sm text-red-300">{error}</p>}<button disabled={busy} className="mt-6 w-full rounded-xl bg-cyan-400 p-3 font-bold text-black">{busy?'Creating…':'Create account'}</button><a href="/login" className="mt-5 block text-center text-sm text-cyan-300">Already have an account? Sign in</a></form></main>
}
